# Site settings
title: Rui Gil
description: >
  Computer Engineer, singer-songwriter, and occasional writer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ruipgil.com" # the base hostname & protocol for your site
email: "ruipgil@gmail.com"
twitter_username: ruipgil
github_username:  ruipgil

# Build settings
markdown: redcarpet
highlighter: pygments

redcarpet:
  extensions: ["strikethrough"]

kramdown:
  input: GFM
  syntax_highlighter: Pygments
