# Site settings
title: Rui Gil
description: >
  Computer Engineer, singer-songwriter, and occasional writer
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ruipgil.com" # the base hostname & protocol for your site
email: "ruipgil@gmail.com"
twitter_username: ruipgil
github_username:  ruipgil
instagram_username:  ruipgil
ga: UA-54125554-4

# Build settings
markdown: kramdown
highlighter: rouge

kramdown:
  input:          GFM
  syntax_highlighter: rouge

